'use client'
import {useEffect,useState} from 'react'
import {Home,ClipboardList,Plus,CheckSquare,Menu,Search,Clock,CheckCircle2,AlertCircle,ChevronRight,X,Trash2,Building2,Users,FolderKanban,CalendarDays,Bell,ShieldCheck,UserRoundCheck,RotateCcw,Send,ArrowLeft,BriefcaseBusiness} from 'lucide-react'

const today='2026-08-10'
const departments=['Management','Operations','Technology','Finance','Marketing']
const members=[
{id:'u1',name:'Almunirah Alam',role:'Super Admin',department:'Management',initials:'AA',color:'#2563eb'},
{id:'u2',name:'Effendy Sarmin',role:'Department Head',department:'Technology',initials:'ES',color:'#7c3aed'},
{id:'u3',name:'Amir Faris',role:'Project Manager',department:'Operations',initials:'AF',color:'#0f9f8f'},
{id:'u4',name:'Sarah Lee',role:'Staff',department:'Finance',initials:'SL',color:'#e39a19'},
{id:'u5',name:'Nadia Rahman',role:'Staff',department:'Marketing',initials:'NR',color:'#e24d4d'}]
const seedProjects=[
{id:'p1',name:'DOSZ Mobile App',description:'Mobile operations and customer experience platform',department:'Technology',ownerId:'u2',due:'2026-08-25',priority:'High',status:'In Progress',color:'#4f7cff'},
{id:'p2',name:'Corporate Website',description:'Organization website refresh and content migration',department:'Marketing',ownerId:'u5',due:'2026-09-05',priority:'Medium',status:'In Progress',color:'#7c3aed'},
{id:'p3',name:'Outlet Operations Review',description:'Standardize operating procedures across outlets',department:'Operations',ownerId:'u3',due:'2026-08-30',priority:'High',status:'Planning',color:'#0f9f8f'}]
const seedTasks=[
{id:'t1',projectId:'p1',title:'Prepare Project Proposal',description:'Prepare scope, budget, timeline and implementation proposal.',assigneeId:'u2',department:'Technology',due:'2026-08-10',time:'14:00',priority:'High',status:'In Progress',checklist:[{id:'c1',text:'Define scope',done:true},{id:'c2',text:'Prepare budget',done:false},{id:'c3',text:'Draft timeline',done:false}]},
{id:'t2',projectId:'p1',title:'Review Mobile Dashboard UI',description:'Review dashboard against corporate UI standards.',assigneeId:'u1',department:'Management',due:'2026-08-10',time:'16:30',priority:'Medium',status:'To Do',checklist:[{id:'c4',text:'Check navigation',done:false},{id:'c5',text:'Check accessibility',done:false}]},
{id:'t3',projectId:'p2',title:'Finalize Homepage Content',description:'Finalize organization messaging and homepage content.',assigneeId:'u5',department:'Marketing',due:'2026-08-11',time:'10:00',priority:'Urgent',status:'Submitted',checklist:[{id:'c6',text:'Draft copy',done:true},{id:'c7',text:'Management review',done:true}]},
{id:'t4',projectId:'p3',title:'Compile Outlet SOP Checklist',description:'Compile outlet operational control checklist.',assigneeId:'u3',department:'Operations',due:'2026-08-09',time:'17:00',priority:'High',status:'In Progress',checklist:[{id:'c8',text:'Opening SOP',done:true},{id:'c9',text:'Closing SOP',done:false}]},
{id:'t5',projectId:'p2',title:'Approve Website Budget',description:'Review and approve website budget allocation.',assigneeId:'u4',department:'Finance',due:'2026-08-10',time:'11:00',priority:'Medium',status:'Completed',checklist:[{id:'c10',text:'Verify quotation',done:true},{id:'c11',text:'Approve allocation',done:true}]}
]
const seedNotifications=[
{id:'n1',type:'task',title:'New task assigned',message:'Review Mobile Dashboard UI has been assigned to you.',time:'9:10 AM',read:false},
{id:'n2',type:'approval',title:'Task submitted for review',message:'Finalize Homepage Content is waiting for approval.',time:'9:35 AM',read:false},
{id:'n3',type:'due',title:'Deadline today',message:'Prepare Project Proposal is due today at 2:00 PM.',time:'10:00 AM',read:true}
]

export default function App(){
 const [tab,setTab]=useState('Dashboard');const [projects,setProjects]=useState(seedProjects);const [tasks,setTasks]=useState(seedTasks);const [notifications,setNotifications]=useState(seedNotifications);const [modal,setModal]=useState(null);const [selectedTask,setSelectedTask]=useState(null);const [query,setQuery]=useState('');const [currentUserId,setCurrentUserId]=useState('u1')
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('mytask-org-v2'));if(d){setProjects(d.projects||seedProjects);setTasks(d.tasks||seedTasks);setNotifications(d.notifications||seedNotifications)}}catch{}},[])
 useEffect(()=>{localStorage.setItem('mytask-org-v2',JSON.stringify({projects,tasks,notifications}))},[projects,tasks,notifications])
 const currentUser=members.find(m=>m.id===currentUserId);const project=id=>projects.find(p=>p.id===id);const member=id=>members.find(m=>m.id===id);const isManager=['Super Admin','Department Head','Project Manager'].includes(currentUser.role);const isOverdue=t=>!['Completed','Approved'].includes(t.status)&&t.due<today
 const visibleTasks=currentUser.role==='Super Admin'?tasks:currentUser.role==='Department Head'?tasks.filter(t=>t.department===currentUser.department):tasks.filter(t=>t.assigneeId===currentUserId)
 const filtered=visibleTasks.filter(t=>(t.title+' '+(project(t.projectId)?.name||'')+' '+(member(t.assigneeId)?.name||'')+' '+t.department).toLowerCase().includes(query.toLowerCase()))
 const stats={total:visibleTasks.length,completed:visibleTasks.filter(t=>['Completed','Approved'].includes(t.status)).length,progress:visibleTasks.filter(t=>t.status==='In Progress').length,overdue:visibleTasks.filter(isOverdue).length}
 function notify(title,message,type='task'){setNotifications(n=>[{id:crypto.randomUUID(),title,message,type,time:'Now',read:false},...n])}
 function addTask(e){e.preventDefault();const f=new FormData(e.currentTarget);const assigneeId=f.get('assigneeId');const m=member(assigneeId);setTasks(x=>[{id:crypto.randomUUID(),title:f.get('title'),description:f.get('description')||'',projectId:f.get('projectId'),assigneeId,department:m?.department||currentUser.department,due:f.get('due')||today,time:f.get('time')||'17:00',priority:f.get('priority'),status:'To Do',checklist:[]},...x]);notify('New task assigned',`${f.get('title')} assigned to ${m?.name||'team member'}.`);setModal(null)}
 function addProject(e){e.preventDefault();const f=new FormData(e.currentTarget);setProjects(x=>[{id:crypto.randomUUID(),name:f.get('name'),description:f.get('description')||'',department:f.get('department'),ownerId:f.get('ownerId'),due:f.get('due')||'2026-08-31',priority:f.get('priority'),status:'Planning',color:'#4f7cff'},...x]);setModal(null)}
 function setStatus(id,status){setTasks(x=>x.map(t=>t.id===id?{...t,status}:t));const t=tasks.find(t=>t.id===id);notify(status==='Submitted'?'Task submitted':'Task status updated',`${t?.title||'Task'} is now ${status}.`,status==='Submitted'?'approval':'task')}
 function toggleChecklist(taskId,itemId){setTasks(x=>x.map(t=>t.id===taskId?{...t,checklist:t.checklist.map(c=>c.id===itemId?{...c,done:!c.done}:c)}:t));setSelectedTask(s=>s&&s.id===taskId?{...s,checklist:s.checklist.map(c=>c.id===itemId?{...c,done:!c.done}:c)}:s)}
 function approval(id,decision){setStatus(id,decision==='approve'?'Approved':'Returned');notify(decision==='approve'?'Task approved':'Task returned',`${tasks.find(t=>t.id===id)?.title} has been ${decision==='approve'?'approved':'returned for revision'}.`,'approval')}
 const nav=[['Dashboard',Home],['My Tasks',ClipboardList],['Approvals',CheckSquare],['More',Menu]]
 return <div className="shell"><main>
 <header><div><span className="eyebrow">MYTASK ORGANIZATION</span><h1>{tab}</h1><div className="orgLine"><Building2 size={13}/> Ezytech Workspace · {currentUser.role}</div></div><div className="headerActions"><button className="bellBtn" onClick={()=>setModal('notifications')}><Bell/>{notifications.filter(n=>!n.read).length>0&&<i>{notifications.filter(n=>!n.read).length}</i>}</button><button className="avatar">{currentUser.initials}</button></div></header>
 <div className="roleSwitch"><ShieldCheck size={14}/><select value={currentUserId} onChange={e=>setCurrentUserId(e.target.value)}>{members.map(m=><option value={m.id} key={m.id}>{m.name} — {m.role}</option>)}</select></div>
 {tab==='Dashboard'&&<Dashboard query={query} setQuery={setQuery} stats={stats} tasks={query?filtered:visibleTasks} project={project} member={member} isOverdue={isOverdue} onOpen={setSelectedTask}/>} 
 {tab==='My Tasks'&&<MyTasks tasks={visibleTasks.filter(t=>t.assigneeId===currentUserId||currentUser.role==='Super Admin')} project={project} member={member} isOverdue={isOverdue} onOpen={setSelectedTask}/>} 
 {tab==='Approvals'&&<Approvals tasks={tasks} project={project} member={member} canApprove={isManager} onApprove={approval} onOpen={setSelectedTask}/>} 
 {tab==='More'&&<MoreMenu setTab={setTab} setModal={setModal}/>} 
 {tab==='Projects'&&<Projects projects={projects} tasks={tasks} member={member} onAdd={()=>setModal('project')}/>} 
 {tab==='Team'&&<Team tasks={tasks}/>} 
 {tab==='Calendar'&&<Calendar tasks={visibleTasks} project={project} member={member}/>} 
 </main>
 <nav><button className={tab==='Dashboard'?'active':''} onClick={()=>setTab('Dashboard')}><Home/><span>Home</span></button><button className={tab==='My Tasks'?'active':''} onClick={()=>setTab('My Tasks')}><ClipboardList/><span>My Tasks</span></button><button className="add" onClick={()=>setModal('task')}><Plus/></button><button className={tab==='Approvals'?'active':''} onClick={()=>setTab('Approvals')}><CheckSquare/><span>Approvals</span></button><button className={tab==='More'?'active':''} onClick={()=>setTab('More')}><Menu/><span>More</span></button></nav>
 {selectedTask&&<TaskDetail task={selectedTask} project={project(selectedTask.projectId)} assignee={member(selectedTask.assigneeId)} currentUser={currentUser} canApprove={isManager} close={()=>setSelectedTask(null)} setStatus={setStatus} toggleChecklist={toggleChecklist} approval={approval}/>} 
 {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='task'?<TaskForm projects={projects} submit={addTask}/>:modal==='project'?<ProjectForm submit={addProject}/>:<Notifications items={notifications} markAll={()=>setNotifications(n=>n.map(x=>({...x,read:true})))}/>}</div></div>}
 </div>
}

function Dashboard({query,setQuery,stats,tasks,project,member,isOverdue,onOpen}){const completion=stats.total?Math.round(stats.completed/stats.total*100):0;return <><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search task, project, staff or department..."/></div><section className="hero orgHero"><div><span>Organization Performance</span><strong>{completion}% Completion</strong><small>{stats.completed} of {stats.total} visible tasks completed</small></div><div className="ring">{completion}%</div></section><div className="orgKpis"><Kpi label="Total Tasks" n={stats.total} icon={<BriefcaseBusiness/>} cls="blue"/><Kpi label="Completed" n={stats.completed} icon={<CheckCircle2/>} cls="green"/><Kpi label="In Progress" n={stats.progress} icon={<Clock/>} cls="amber"/><Kpi label="Overdue" n={stats.overdue} icon={<AlertCircle/>} cls="red"/></div><Title text="Team Workload"/><div className="workload">{members.slice(0,4).map(m=>{const mt=tasks.filter(t=>t.assigneeId===m.id&&!['Completed','Approved'].includes(t.status)).length;return <div className="workMember" key={m.id}><Avatar m={m}/><div><b>{m.name}</b><small>{m.department}</small></div><span>{mt} active</span></div>})}</div><Title text={query?'Search Results':'Organization Tasks'}/><div className="list">{tasks.map(t=><TaskRow key={t.id} t={t} project={project(t.projectId)} assignee={member(t.assigneeId)} overdue={isOverdue(t)} onOpen={()=>onOpen(t)}/>)}</div></>}
function MyTasks({tasks,project,member,isOverdue,onOpen}){const todayList=tasks.filter(t=>t.due===today&&!['Completed','Approved'].includes(t.status)),upcoming=tasks.filter(t=>t.due>today&&!['Completed','Approved'].includes(t.status)),done=tasks.filter(t=>['Completed','Approved'].includes(t.status));return <><section className="myTaskHero"><ClipboardList/><div><span>Personal Work Queue</span><strong>{tasks.filter(t=>!['Completed','Approved'].includes(t.status)).length} Active Tasks</strong><small>Focus on your assigned responsibilities</small></div></section><TaskSection title="Due Today" items={todayList}/><TaskSection title="Upcoming" items={upcoming}/><TaskSection title="Completed" items={done}/></>;function TaskSection({title,items}){return <><Title text={`${title} (${items.length})`}/><div className="list">{items.length?items.map(t=><TaskRow key={t.id} t={t} project={project(t.projectId)} assignee={member(t.assigneeId)} overdue={isOverdue(t)} onOpen={()=>onOpen(t)}/>):<div className="miniEmpty">No tasks in this section.</div>}</div></>}}
function Approvals({tasks,project,member,canApprove,onApprove,onOpen}){const pending=tasks.filter(t=>t.status==='Submitted'),returned=tasks.filter(t=>t.status==='Returned');return <><section className="approvalHero"><CheckSquare/><div><span>Approval Centre</span><strong>{pending.length} Waiting for Review</strong><small>{canApprove?'You can approve or return submitted work.':'You have view-only access.'}</small></div></section><Title text="Pending Approval"/><div className="list">{pending.length?pending.map(t=><article className="approvalCard" key={t.id} onClick={()=>onOpen(t)}><Avatar m={member(t.assigneeId)}/><div><b>{t.title}</b><small>{project(t.projectId)?.name} · {member(t.assigneeId)?.name}</small><span>Submitted for review</span></div>{canApprove&&<div className="approvalActions" onClick={e=>e.stopPropagation()}><button className="approve" onClick={()=>onApprove(t.id,'approve')}>Approve</button><button className="return" onClick={()=>onApprove(t.id,'return')}>Return</button></div>}</article>):<div className="miniEmpty">No approvals pending.</div>}</div>{returned.length>0&&<><Title text="Returned for Revision"/><div className="list">{returned.map(t=><TaskRow key={t.id} t={t} project={project(t.projectId)} assignee={member(t.assigneeId)} onOpen={()=>onOpen(t)}/>)}</div></>}</>}
function MoreMenu({setTab,setModal}){const items=[['Projects',FolderKanban,'Organization projects'],['Team',Users,'Members & departments'],['Calendar',CalendarDays,'Deadlines & milestones'],['Notifications',Bell,'Assignments and approval alerts']];return <><section className="moreHero"><Building2/><div><span>Organization</span><strong>Workspace Modules</strong><small>Access management and collaboration tools</small></div></section><div className="moreGrid">{items.map(([name,I,desc])=><button key={name} onClick={()=>name==='Notifications'?setModal('notifications'):setTab(name)}><I/><div><b>{name}</b><small>{desc}</small></div><ChevronRight/></button>)}</div><Title text="Organization Structure"/><div className="orgTree"><div className="orgRoot"><Building2/> Ezytech Workspace</div>{departments.map(d=><div className="orgDept" key={d}><span>{d}</span><small>{members.filter(m=>m.department===d).map(m=>m.name).join(' · ')||'No members'}</small></div>)}</div></>}
function TaskDetail({task,project,assignee,currentUser,canApprove,close,setStatus,toggleChecklist,approval}){const pct=task.checklist.length?Math.round(task.checklist.filter(c=>c.done).length/task.checklist.length*100):0;return <div className="detailOverlay"><div className="detailPage"><div className="detailTop"><button onClick={close}><ArrowLeft/></button><span>Task Details</span><button onClick={close}><X/></button></div><div className="detailHeader"><div><span className={'priority '+task.priority.toLowerCase()}>{task.priority}</span><h2>{task.title}</h2><p>{project?.name} · {task.department}</p></div><Avatar m={assignee}/></div><div className="detailMeta"><div><small>Assigned to</small><b>{assignee?.name}</b></div><div><small>Due</small><b>{task.due} {task.time}</b></div><div><small>Status</small><b>{task.status}</b></div></div><section className="detailSection"><h3>Description</h3><p>{task.description||'No description provided.'}</p></section><section className="detailSection"><div className="checkTitle"><h3>Checklist</h3><span>{pct}%</span></div><div className="checkProgress"><i style={{width:pct+'%'}}/></div><div className="checkItems">{task.checklist.length?task.checklist.map(c=><label key={c.id}><input type="checkbox" checked={c.done} onChange={()=>toggleChecklist(task.id,c.id)}/><span className={c.done?'doneText':''}>{c.text}</span></label>):<p>No checklist items.</p>}</div></section><div className="detailActions">{task.assigneeId===currentUser.id&&['To Do','In Progress','Returned'].includes(task.status)&&<><button onClick={()=>setStatus(task.id,'In Progress')}><Clock/> Start Work</button><button className="submitBtn" onClick={()=>setStatus(task.id,'Submitted')}><Send/> Submit for Review</button></>}{canApprove&&task.status==='Submitted'&&<><button className="approveBtn" onClick={()=>approval(task.id,'approve')}><CheckCircle2/> Approve</button><button className="returnBtn" onClick={()=>approval(task.id,'return')}><RotateCcw/> Return</button></>}</div></div></div>}
function Notifications({items,markAll}){return <><div className="sheetTitle"><div><h2>Notifications</h2><p>{items.filter(n=>!n.read).length} unread notifications</p></div><button onClick={markAll}>Mark all read</button></div><div className="notificationList">{items.map(n=><div className={'notification '+(!n.read?'unread':'')} key={n.id}><span className={'notifIcon '+n.type}>{n.type==='approval'?<CheckSquare/>:n.type==='due'?<Clock/>:<Bell/>}</span><div><b>{n.title}</b><p>{n.message}</p><small>{n.time}</small></div></div>)}</div></>}
function TaskRow({t,project,assignee,overdue,onOpen}){return <article className="task orgTask clickable" onClick={onOpen}><span className={'check '+(['Completed','Approved'].includes(t.status)?'done':'')}>{['Completed','Approved'].includes(t.status)&&'✓'}</span><div className="taskBody"><div className="taskTitleRow"><h3 className={['Completed','Approved'].includes(t.status)?'strike':''}>{t.title}</h3><Avatar m={assignee} size="mini"/></div><p>{project?.name||'General'} · {t.department}</p><div><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span><span className={'statusTag '+t.status.toLowerCase().replaceAll(' ','-')}>{t.status}</span><span className={overdue?'late':''}>{overdue?'Overdue':t.due+' '+t.time}</span></div><div className="assigned"><UserRoundCheck size={13}/> {assignee?.name||'Unassigned'}</div></div><ChevronRight size={16}/></article>}
function Kpi({label,n,icon,cls}){return <div className={'orgKpi '+cls}><span>{icon}</span><b>{n}</b><small>{label}</small></div>}
function Title({text,action,onClick}){return <div className="title"><h2>{text}</h2>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Avatar({m,size=''}){return <span className={'memberAvatar '+size} style={{background:m?.color||'#60758a'}}>{m?.initials||'--'}</span>}
function Projects({projects,tasks,member,onAdd}){return <><Title text="Organization Projects" action="New Project" onClick={onAdd}/><div className="projects">{projects.map(p=>{const pt=tasks.filter(t=>t.projectId===p.id),done=pt.filter(t=>['Completed','Approved'].includes(t.status)).length,progress=pt.length?Math.round(done/pt.length*100):0,owner=member(p.ownerId);return <article className="project" key={p.id}><div className="projectTop"><span className="projectIcon" style={{background:p.color}}>{p.name[0]}</span><span className="pill">{p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="projectOwner"><Avatar m={owner} size="mini"/><span><b>{owner?.name}</b><small>{p.department} · Project Owner</small></span></div><div className="progress"><i style={{width:progress+'%',background:p.color}}/></div><div className="projectMeta"><b>{progress}% Complete</b><span>{done} / {pt.length} Tasks</span></div><small>Due {p.due}</small></article>})}</div></>}
function Team({tasks}){return <><section className="teamSummary"><Users/><div><span>Organization Team</span><strong>{members.length} Members</strong><small>{departments.length} Departments</small></div></section><Title text="Members & Workload"/><div className="teamList">{members.map(m=>{const assigned=tasks.filter(t=>t.assigneeId===m.id),active=assigned.filter(t=>!['Completed','Approved'].includes(t.status)).length,done=assigned.filter(t=>['Completed','Approved'].includes(t.status)).length;return <article className="teamCard" key={m.id}><Avatar m={m}/><div className="teamInfo"><b>{m.name}</b><span>{m.role}</span><small>{m.department}</small></div><div className="teamNumbers"><b>{active}</b><small>Active</small><b>{done}</b><small>Done</small></div></article>})}</div></>}
function Calendar({tasks,project,member}){const [day,setDay]=useState(today);const days=Array.from({length:31},(_,i)=>`2026-08-${String(i+1).padStart(2,'0')}`);return <><div className="month"><h2>Organization Calendar · August 2026</h2><div className="grid">{['M','T','W','T','F','S','S'].map((x,i)=><b key={i}>{x}</b>)}{Array(5).fill(0).map((_,i)=><i key={'x'+i}/>)}{days.map((d,i)=><button key={d} onClick={()=>setDay(d)} className={day===d?'selected':''}>{i+1}{tasks.some(t=>t.due===d)&&<em/>}</button>)}</div></div><Title text={day===today?'Today':day}/><div className="list">{tasks.filter(t=>t.due===day).map(t=><div className="calendarTask" key={t.id}><span>{t.time}</span><Avatar m={member(t.assigneeId)} size="mini"/><div><b>{t.title}</b><small>{project(t.projectId)?.name} · {member(t.assigneeId)?.name}</small></div><ChevronRight/></div>)}</div></>}
function TaskForm({projects,submit}){return <form onSubmit={submit}><h2>Assign New Task</h2><label>Task Name<input name="title" required autoFocus placeholder="Task to be completed"/></label><label>Description<textarea name="description" placeholder="Task scope / expected outcome"/></label><label>Project<select name="projectId">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Assign To<select name="assigneeId">{members.map(m=><option value={m.id} key={m.id}>{m.name} — {m.department}</option>)}</select></label><div className="row"><label>Due Date<input name="due" type="date" defaultValue={today}/></label><label>Due Time<input name="time" type="time" defaultValue="17:00"/></label></div><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><button className="primary">Assign Task</button></form>}
function ProjectForm({submit}){return <form onSubmit={submit}><h2>Create Organization Project</h2><label>Project Name<input name="name" required autoFocus placeholder="Project name"/></label><label>Description<textarea name="description" placeholder="Project scope / objective"/></label><label>Department<select name="department">{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Project Owner<select name="ownerId">{members.map(m=><option value={m.id} key={m.id}>{m.name} — {m.role}</option>)}</select></label><div className="row"><label>Due Date<input name="due" type="date"/></label><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label></div><button className="primary">Create Project</button></form>}
