'use client'
import {useEffect,useState} from 'react'
import {Home,FolderKanban,Plus,CalendarDays,Users,Search,Clock,CheckCircle2,AlertCircle,ChevronRight,X,Trash2,Building2,UserRoundCheck,BriefcaseBusiness} from 'lucide-react'

const today='2026-08-10'
const departments=['Management','Operations','Technology','Finance','Marketing']
const members=[
{id:'u1',name:'Almunirah Alam',role:'Administrator',department:'Management',initials:'AA',color:'#2f6fed'},
{id:'u2',name:'Effendy Sarmin',role:'Project Lead',department:'Technology',initials:'ES',color:'#7c3aed'},
{id:'u3',name:'Amir Faris',role:'Operations Lead',department:'Operations',initials:'AF',color:'#0f9f8f'},
{id:'u4',name:'Sarah Lee',role:'Finance Executive',department:'Finance',initials:'SL',color:'#e39a19'},
{id:'u5',name:'Nadia Rahman',role:'Marketing Executive',department:'Marketing',initials:'NR',color:'#e24d4d'}]
const seedProjects=[
{id:'p1',name:'DOSZ Mobile App',description:'Mobile operations and customer experience platform',department:'Technology',ownerId:'u2',due:'2026-08-25',priority:'High',status:'In Progress',color:'#4f7cff'},
{id:'p2',name:'Corporate Website',description:'Organization website refresh and content migration',department:'Marketing',ownerId:'u5',due:'2026-09-05',priority:'Medium',status:'In Progress',color:'#7c3aed'},
{id:'p3',name:'Outlet Operations Review',description:'Standardize operating procedures across outlets',department:'Operations',ownerId:'u3',due:'2026-08-30',priority:'High',status:'Planning',color:'#0f9f8f'}]
const seedTasks=[
{id:'t1',projectId:'p1',title:'Prepare Project Proposal',assigneeId:'u2',department:'Technology',due:'2026-08-10',time:'14:00',priority:'High',status:'In Progress'},
{id:'t2',projectId:'p1',title:'Review Mobile Dashboard UI',assigneeId:'u1',department:'Management',due:'2026-08-10',time:'16:30',priority:'Medium',status:'To Do'},
{id:'t3',projectId:'p2',title:'Finalize Homepage Content',assigneeId:'u5',department:'Marketing',due:'2026-08-11',time:'10:00',priority:'Urgent',status:'To Do'},
{id:'t4',projectId:'p3',title:'Compile Outlet SOP Checklist',assigneeId:'u3',department:'Operations',due:'2026-08-09',time:'17:00',priority:'High',status:'In Progress'},
{id:'t5',projectId:'p2',title:'Approve Website Budget',assigneeId:'u4',department:'Finance',due:'2026-08-10',time:'11:00',priority:'Medium',status:'Completed'}]

export default function App(){
 const [tab,setTab]=useState('Dashboard');const [projects,setProjects]=useState(seedProjects);const [tasks,setTasks]=useState(seedTasks);const [modal,setModal]=useState(null);const [query,setQuery]=useState('');
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('mytask-org-data'));if(d){setProjects(d.projects||seedProjects);setTasks(d.tasks||seedTasks)}}catch{}},[])
 useEffect(()=>{localStorage.setItem('mytask-org-data',JSON.stringify({projects,tasks}))},[projects,tasks])
 const project=id=>projects.find(p=>p.id===id);const member=id=>members.find(m=>m.id===id);const isOverdue=t=>t.status!=='Completed'&&t.due<today;const complete=id=>setTasks(x=>x.map(t=>t.id===id?{...t,status:t.status==='Completed'?'To Do':'Completed'}:t));
 const filtered=tasks.filter(t=>(t.title+' '+(project(t.projectId)?.name||'')+' '+(member(t.assigneeId)?.name||'')+' '+t.department).toLowerCase().includes(query.toLowerCase()));
 const stats={total:tasks.length,completed:tasks.filter(t=>t.status==='Completed').length,progress:tasks.filter(t=>t.status==='In Progress').length,overdue:tasks.filter(isOverdue).length};
 function addTask(e){e.preventDefault();const f=new FormData(e.currentTarget);const assigneeId=f.get('assigneeId');const m=member(assigneeId);setTasks(x=>[{id:crypto.randomUUID(),title:f.get('title'),projectId:f.get('projectId'),assigneeId,department:m?.department||f.get('department'),due:f.get('due')||today,time:f.get('time')||'17:00',priority:f.get('priority'),status:'To Do'},...x]);setModal(null)}
 function addProject(e){e.preventDefault();const f=new FormData(e.currentTarget);setProjects(x=>[{id:crypto.randomUUID(),name:f.get('name'),description:f.get('description')||'',department:f.get('department'),ownerId:f.get('ownerId'),due:f.get('due')||'2026-08-31',priority:f.get('priority'),status:'Planning',color:'#4f7cff'},...x]);setModal(null)}
 return <div className="shell"><main>
 <header><div><span className="eyebrow">MYTASK ORGANIZATION</span><h1>{tab==='Dashboard'?'Organization Workspace':tab}</h1><div className="orgLine"><Building2 size={13}/> Ezytech Workspace · Administrator</div></div><button className="avatar">AA</button></header>
 {tab==='Dashboard'&&<Dashboard query={query} setQuery={setQuery} stats={stats} tasks={query?filtered:tasks} projects={projects} project={project} member={member} complete={complete} remove={id=>setTasks(x=>x.filter(a=>a.id!==id))} isOverdue={isOverdue}/>} 
 {tab==='Projects'&&<Projects projects={projects} tasks={tasks} member={member} onAdd={()=>setModal('project')}/>} 
 {tab==='Calendar'&&<Calendar tasks={tasks} project={project} member={member}/>} 
 {tab==='Team'&&<Team tasks={tasks}/>} 
 </main>
 <nav>{[['Dashboard',Home],['Projects',FolderKanban]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}<button className="add" onClick={()=>setModal('task')}><Plus/></button>{[['Calendar',CalendarDays],['Team',Users]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}</nav>
 {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='task'?<TaskForm projects={projects} submit={addTask}/>:<ProjectForm submit={addProject}/>}</div></div>}
 </div>
}

function Dashboard({query,setQuery,stats,tasks,projects,project,member,complete,remove,isOverdue}){const completion=stats.total?Math.round(stats.completed/stats.total*100):0;return <>
 <div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search task, project, staff or department..."/></div>
 <section className="hero orgHero"><div><span>Organization Performance</span><strong>{completion}% Completion</strong><small>{stats.completed} of {stats.total} tasks completed</small></div><div className="ring">{completion}%</div></section>
 <div className="orgKpis"><Kpi label="Total Tasks" n={stats.total} icon={<BriefcaseBusiness/>} cls="blue"/><Kpi label="Completed" n={stats.completed} icon={<CheckCircle2/>} cls="green"/><Kpi label="In Progress" n={stats.progress} icon={<Clock/>} cls="amber"/><Kpi label="Overdue" n={stats.overdue} icon={<AlertCircle/>} cls="red"/></div>
 <Title text="Team Workload"/><div className="workload">{members.slice(0,4).map(m=>{const mt=tasks.filter(t=>t.assigneeId===m.id&&t.status!=='Completed').length;return <div className="workMember" key={m.id}><Avatar m={m}/><div><b>{m.name}</b><small>{m.department}</small></div><span>{mt} active</span></div>})}</div>
 <Title text={query?'Search Results':'Organization Tasks'}/><div className="list">{tasks.map(t=><Task key={t.id} t={t} project={project(t.projectId)} assignee={member(t.assigneeId)} complete={complete} remove={()=>remove(t.id)} overdue={isOverdue(t)}/>)}</div>
 </>}
function Kpi({label,n,icon,cls}){return <div className={'orgKpi '+cls}><span>{icon}</span><b>{n}</b><small>{label}</small></div>}
function Title({text,action,onClick}){return <div className="title"><h2>{text}</h2>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Avatar({m,size=''}){return <span className={'memberAvatar '+size} style={{background:m?.color||'#60758a'}}>{m?.initials||'--'}</span>}
function Task({t,project,assignee,complete,remove,overdue}){return <article className="task orgTask"><button className={'check '+(t.status==='Completed'?'done':'')} onClick={()=>complete(t.id)}>{t.status==='Completed'&&'✓'}</button><div className="taskBody"><div className="taskTitleRow"><h3 className={t.status==='Completed'?'strike':''}>{t.title}</h3><Avatar m={assignee} size="mini"/></div><p>{project?.name||'General'} · {t.department}</p><div><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span><span className={'statusTag '+t.status.toLowerCase().replaceAll(' ','-')}>{t.status}</span><span className={overdue?'late':''}>{overdue?'Overdue':t.due+' '+t.time}</span></div><div className="assigned"><UserRoundCheck size={13}/> Assigned to {assignee?.name||'Unassigned'}</div></div><button className="trash" onClick={remove}><Trash2 size={17}/></button></article>}
function Projects({projects,tasks,member,onAdd}){return <><Title text="Organization Projects" action="New Project" onClick={onAdd}/><div className="projects">{projects.map(p=>{const pt=tasks.filter(t=>t.projectId===p.id),done=pt.filter(t=>t.status==='Completed').length,progress=pt.length?Math.round(done/pt.length*100):0,owner=member(p.ownerId);return <article className="project" key={p.id}><div className="projectTop"><span className="projectIcon" style={{background:p.color}}>{p.name[0]}</span><span className="pill">{p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="projectOwner"><Avatar m={owner} size="mini"/><span><b>{owner?.name}</b><small>{p.department} · Project Owner</small></span></div><div className="progress"><i style={{width:progress+'%',background:p.color}}/></div><div className="projectMeta"><b>{progress}% Complete</b><span>{done} / {pt.length} Tasks</span></div><small>Due {p.due}</small></article>})}</div></>}
function Team({tasks}){return <><section className="teamSummary"><Users/><div><span>Organization Team</span><strong>{members.length} Members</strong><small>{departments.length} Departments</small></div></section><Title text="Members & Workload"/><div className="teamList">{members.map(m=>{const assigned=tasks.filter(t=>t.assigneeId===m.id),active=assigned.filter(t=>t.status!=='Completed').length,done=assigned.filter(t=>t.status==='Completed').length;return <article className="teamCard" key={m.id}><Avatar m={m}/><div className="teamInfo"><b>{m.name}</b><span>{m.role}</span><small>{m.department}</small></div><div className="teamNumbers"><b>{active}</b><small>Active</small><b>{done}</b><small>Done</small></div></article>})}</div><Title text="Departments"/><div className="deptGrid">{departments.map(d=><div key={d}><span>{d}</span><b>{members.filter(m=>m.department===d).length}</b><small>members</small></div>)}</div></>}
function TaskForm({projects,submit}){return <form onSubmit={submit}><h2>Assign New Task</h2><label>Task Name<input name="title" required autoFocus placeholder="Task to be completed"/></label><label>Project<select name="projectId">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Assign To<select name="assigneeId">{members.map(m=><option value={m.id} key={m.id}>{m.name} — {m.department}</option>)}</select></label><div className="row"><label>Due Date<input name="due" type="date" defaultValue={today}/></label><label>Due Time<input name="time" type="time" defaultValue="17:00"/></label></div><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><button className="primary">Assign Task</button></form>}
function ProjectForm({submit}){return <form onSubmit={submit}><h2>Create Organization Project</h2><label>Project Name<input name="name" required autoFocus placeholder="Project name"/></label><label>Description<textarea name="description" placeholder="Project scope / objective"/></label><label>Department<select name="department">{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Project Owner<select name="ownerId">{members.map(m=><option value={m.id} key={m.id}>{m.name} — {m.role}</option>)}</select></label><div className="row"><label>Due Date<input name="due" type="date"/></label><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label></div><button className="primary">Create Project</button></form>}
function Calendar({tasks,project,member}){const [day,setDay]=useState(today);const days=Array.from({length:31},(_,i)=>`2026-08-${String(i+1).padStart(2,'0')}`);return <><div className="month"><h2>Organization Calendar · August 2026</h2><div className="grid">{['M','T','W','T','F','S','S'].map((x,i)=><b key={i}>{x}</b>)}{Array(5).fill(0).map((_,i)=><i key={'x'+i}/>)}{days.map((d,i)=><button key={d} onClick={()=>setDay(d)} className={day===d?'selected':''}>{i+1}{tasks.some(t=>t.due===d)&&<em/>}</button>)}</div></div><Title text={day===today?'Today':day}/><div className="list">{tasks.filter(t=>t.due===day).map(t=><div className="calendarTask" key={t.id}><span>{t.time}</span><Avatar m={member(t.assigneeId)} size="mini"/><div><b>{t.title}</b><small>{project(t.projectId)?.name} · {member(t.assigneeId)?.name}</small></div><ChevronRight/></div>)}</div></>}
