'use client'
import {useEffect,useMemo,useState} from 'react'
import {Home,FolderKanban,Plus,CalendarDays,User,Search,Clock,CheckCircle2,AlertCircle,ChevronRight,X,Trash2} from 'lucide-react'
const seedProjects=[{id:'p1',name:'DOSZ Mobile App',description:'Mobile experience & operations',due:'2026-08-25',priority:'High',status:'In Progress',color:'#6558e8'},{id:'p2',name:'Website Development',description:'Corporate website refresh',due:'2026-09-05',priority:'Medium',status:'In Progress',color:'#0ca678'}]
const seedTasks=[{id:'t1',projectId:'p1',title:'Prepare Project Proposal',due:'2026-08-10',time:'14:00',priority:'High',status:'In Progress'},{id:'t2',projectId:'p1',title:'Review mobile dashboard UI',due:'2026-08-10',time:'16:30',priority:'Medium',status:'To Do'},{id:'t3',projectId:'p2',title:'Finalize homepage content',due:'2026-08-11',time:'10:00',priority:'Urgent',status:'To Do'},{id:'t4',projectId:'p2',title:'Setup project structure',due:'2026-08-09',time:'17:00',priority:'Low',status:'Completed'}]
const today='2026-08-10'
export default function App(){const [tab,setTab]=useState('Home');const [projects,setProjects]=useState(seedProjects);const [tasks,setTasks]=useState(seedTasks);const [modal,setModal]=useState(null);const [query,setQuery]=useState('');
useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('mytask-data'));if(d){setProjects(d.projects||seedProjects);setTasks(d.tasks||seedTasks)}}catch{}},[])
useEffect(()=>{localStorage.setItem('mytask-data',JSON.stringify({projects,tasks}))},[projects,tasks])
const projectName=id=>projects.find(p=>p.id===id)?.name||'Personal';const isOverdue=t=>t.status!=='Completed'&&t.due<today;const todayTasks=tasks.filter(t=>t.due===today);const complete=id=>setTasks(x=>x.map(t=>t.id===id?{...t,status:t.status==='Completed'?'To Do':'Completed'}:t));
const filtered=tasks.filter(t=>(t.title+' '+projectName(t.projectId)).toLowerCase().includes(query.toLowerCase()));
function addTask(e){e.preventDefault();const f=new FormData(e.currentTarget);setTasks(x=>[{id:crypto.randomUUID(),title:f.get('title'),projectId:f.get('projectId'),due:f.get('due')||today,time:f.get('time')||'17:00',priority:f.get('priority'),status:'To Do'},...x]);setModal(null)}
function addProject(e){e.preventDefault();const f=new FormData(e.currentTarget);setProjects(x=>[{id:crypto.randomUUID(),name:f.get('name'),description:f.get('description')||'',due:f.get('due')||'2026-08-31',priority:f.get('priority'),status:'Planning',color:'#6558e8'},...x]);setModal(null)}
const stats={completed:todayTasks.filter(t=>t.status==='Completed').length,progress:todayTasks.filter(t=>t.status==='In Progress').length,overdue:tasks.filter(isOverdue).length};
return <div className="shell"><main><header><div><span className="eyebrow">GOOD MORNING</span><h1>{tab==='Home'?'What are you working on today?':tab}</h1></div><button className="avatar">A</button></header>
{tab==='Home'&&<><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, projects..."/></div><section className="hero"><div><span>Today</span><strong>{todayTasks.length} Tasks</strong></div><div className="ring">{todayTasks.length?Math.round(stats.completed/todayTasks.length*100):0}%</div></section><div className="stats"><Stat n={stats.completed} label="Completed" icon={<CheckCircle2/>}/><Stat n={stats.progress} label="In Progress" icon={<Clock/>}/><Stat n={stats.overdue} label="Overdue" icon={<AlertCircle/>}/></div><Title text={query?'Search Results':"Today's Tasks"}/><div className="list">{(query?filtered:todayTasks).length?(query?filtered:todayTasks).map(t=><Task key={t.id} t={t} project={projectName(t.projectId)} complete={complete} remove={()=>setTasks(x=>x.filter(a=>a.id!==t.id))} overdue={isOverdue(t)}/>):<Empty text="You're all clear for today 🎉"/>}</div></>}
{tab==='Projects'&&<><Title text="Active Projects" action="New Project" onClick={()=>setModal('project')}/><div className="projects">{projects.map(p=>{const pt=tasks.filter(t=>t.projectId===p.id),done=pt.filter(t=>t.status==='Completed').length,progress=pt.length?Math.round(done/pt.length*100):0;return <article className="project" key={p.id}><div className="projectTop"><span className="projectIcon" style={{background:p.color}}>{p.name[0]}</span><span className="pill">{p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="progress"><i style={{width:progress+'%',background:p.color}}/></div><div className="projectMeta"><b>{progress}%</b><span>{done} / {pt.length} Tasks</span></div><small>Due {p.due}</small></article>})}</div></>}
{tab==='Calendar'&&<Calendar tasks={tasks} projectName={projectName}/>} {tab==='Profile'&&<Profile tasks={tasks} projects={projects}/>}</main>
<nav>{[['Home',Home],['Projects',FolderKanban]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}<button className="add" onClick={()=>setModal('task')}><Plus/></button>{[['Calendar',CalendarDays],['Profile',User]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}</nav>
{modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><div className="sheet" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='task'?<TaskForm projects={projects} submit={addTask}/>:<ProjectForm submit={addProject}/>}</div></div>}</div>}
function Stat({n,label,icon}){return <div className="stat"><span>{icon}</span><b>{n}</b><small>{label}</small></div>};function Title({text,action,onClick}){return <div className="title"><h2>{text}</h2>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Task({t,project,complete,remove,overdue}){return <article className="task"><button className={'check '+(t.status==='Completed'?'done':'')} onClick={()=>complete(t.id)}>{t.status==='Completed'&&'✓'}</button><div className="taskBody"><h3 className={t.status==='Completed'?'strike':''}>{t.title}</h3><p>{project}</p><div><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span><span className={overdue?'late':''}>{overdue?'Overdue':t.time}</span></div></div><button className="trash" onClick={remove}><Trash2 size={17}/></button></article>}
function Empty({text}){return <div className="empty"><CheckCircle2/><h3>{text}</h3><p>No tasks scheduled.</p></div>}
function TaskForm({projects,submit}){return <form onSubmit={submit}><h2>Quick Add Task</h2><label>Task Name<input name="title" required autoFocus placeholder="What needs to be done?"/></label><label>Project<select name="projectId">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="row"><label>Due Date<input name="due" type="date" defaultValue={today}/></label><label>Due Time<input name="time" type="time" defaultValue="17:00"/></label></div><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><button className="primary">Add Task</button></form>}
function ProjectForm({submit}){return <form onSubmit={submit}><h2>New Project</h2><label>Project Name<input name="name" required autoFocus placeholder="Project name"/></label><label>Description<textarea name="description" placeholder="Short description"/></label><label>Due Date<input name="due" type="date"/></label><label>Priority<select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><button className="primary">Create Project</button></form>}
function Calendar({tasks,projectName}){const [day,setDay]=useState(today);const days=Array.from({length:31},(_,i)=>`2026-08-${String(i+1).padStart(2,'0')}`);return <><div className="month"><h2>August 2026</h2><div className="grid">{['M','T','W','T','F','S','S'].map((x,i)=><b key={i}>{x}</b>)}{Array(5).fill(0).map((_,i)=><i key={'x'+i}/>)}{days.map((d,i)=><button key={d} onClick={()=>setDay(d)} className={day===d?'selected':''}>{i+1}{tasks.some(t=>t.due===d)&&<em/>}</button>)}</div></div><Title text={day===today?'Today':day}/><div className="list">{tasks.filter(t=>t.due===day).map(t=><div className="calendarTask" key={t.id}><span>{t.time}</span><div><b>{t.title}</b><small>{projectName(t.projectId)}</small></div><ChevronRight/></div>)}</div></>}
function Profile({tasks,projects}){const done=tasks.filter(t=>t.status==='Completed').length;return <><div className="profile"><div className="bigAvatar">A</div><h2>My Productivity</h2><p>Keep moving your projects forward.</p></div><div className="profileStats"><div><b>{done}</b><span>Completed</span></div><div><b>{projects.length}</b><span>Active Projects</span></div><div><b>{tasks.length?Math.round(done/tasks.length*100):0}%</b><span>Completion</span></div></div><Title text="Settings"/><div className="settings">{['Notification Settings','Default Reminder','Theme & Dark Mode','Data Backup','Export Data','Archived Projects'].map(x=><button key={x}>{x}<ChevronRight/></button>)}</div></>}
